docs/HISTORY.txt, ftw/referencewidget/converter.py
@maethu this fixes a bug on relationlist field, that it always self references.
=> ignore empty strings in converter

docs/HISTORY.txt, ftw/referencewidget/templates/handlebars.html, ftw/referencewidget/templates/referencewidget_input.pt, ftw/referencewidget/tests/test_utils.py, ftw/referencewidget/widget.py, test-plone-4.3.x-chameleon.cfg
The original page template implementation in zope.pagetemplate does not render within `<script>`-tags at all, thus the handlebars were not rendered until now.
But chameleon does render `<script>`-tags, but our handlebars are invalid from a page template point of view. Things such as tags with dynamic tagnames produce errors.
Since we cannot render the handlebar templates properly I have extracted them into a separate template so that we can include them statically.
I've also fixed some other errors and added a test configuration with chameleon.
⚠️ I'm unable to tell whether the widget still works or not, as the package contains no development-example and the tests are never really using the widget with a testbrowser (for example removing the templates does not break the tests).
@maethu …
=> Support chameleon by not rendering handlebar templates

README.rst, docs/HISTORY.txt, ftw/referencewidget/configure.zcml, ftw/referencewidget/converter.py, ftw/referencewidget/resources/refwidget.css, ftw/referencewidget/resources/refwidget.js
Purpose:
ftw.news filter_py_path is a list of relation choices, which stores paths. With this change this Widget can be used as drop-in replacement. It stores an loads the same values as the ContentTreeWidget.
This PR also updates the readme with some valuable informations.
Further I made some visual improvements:
- Display only the relevant part of the url (selected items)
- No list styles anymore
=> Implement support for IList of IRelationChoice explicitly.

README.rst, docs/HISTORY.txt, ftw/referencewidget/configure.zcml, ftw/referencewidget/converter.py
This allows the following field/widget combination
``` 
form.widget(link=ReferenceWidgetFactory)
link = schema.TextLine(
title=_(u'label_link', default=u'Link'),
description=_(u'help_link', default=u''),
required=False,
)
```
=> Implement support for ITextLine with ReferenceWidget.

docs/HISTORY.txt, ftw/referencewidget/converter.py
The Referencewidget should respect missing_values of fields so giving an empty value doesn't fail.
=> respect missing_value of field

docs/HISTORY.txt, ftw/referencewidget/widget.py
This fixes a widget render error if:
- The obj has been renamed/moves (also multiple times)
- The obj has been removed.
TESTS:
I know there should be two new testcases, but since there is currently none, I'm not able to write them.
It needs some work in advance... like some test behaviors with fields in order to test the widget with real use-cases.
=> Use plone.app.redirector to follow renamed and moved content.

README.rst, docs/HISTORY.txt, ftw/referencewidget/behaviors.py, ftw/referencewidget/browser/utils.py, ftw/referencewidget/configure.zcml, ftw/referencewidget/sources.py, ftw/referencewidget/testing.py, ftw/referencewidget/tests/__init__.py, ftw/referencewidget/tests/builders.py, ftw/referencewidget/tests/test_related_items_behavior.py, ftw/referencewidget/tests/test_relation_choice.py, ftw/referencewidget/tests/views/form.py, ftw/referencewidget/tests/widgets.py, ftw/referencewidget/widget.py
To demonstrate the ContextSourceBinder there are some behaviors registered along with this package. 
The `IRelatedItems` behavior is a 1 to 1 replacement for the plone.app.relationfield IRelatedItems behavior. There are some more for testing. 
I was trying to not break the old behavior, where all the magic happens in the widget. 
Decisions:
- If there is a RelationChoice or RelationList (with RelationChoice) field the a `source` is more important than the widget config. 
- Other fields does still only respects the config from the widget. 
- If there is the same config on a widget and on the source, the source config will win. 
- Traversal still happens on the widget
- Selectable is in the source for RelationChoice (or list of RelationChoice)
- It's possible to pass a filter method to the …
=> Implement a ObjSourceBinder 

README.rst, docs/HISTORY.txt, ftw/referencewidget/browser/jsongenerator.py, ftw/referencewidget/browser/search.py, ftw/referencewidget/converter.py, ftw/referencewidget/tests/test_json_view.py, ftw/referencewidget/tests/test_search_view.py, ftw/referencewidget/widget.py
This allows us to apply more filter criteria to the traversal query:
Example:
- Filter for object_provides
- Filter for review_state
=> Implement a additional `traversal_query` parameter for the widget.

docs/HISTORY.txt, ftw/referencewidget/resources/refwidget.js, ftw/referencewidget/templates/referencewidget_input.pt, ftw/referencewidget/tests/test_related_items_behavior.py, ftw/referencewidget/tests/test_relation_choice.py, ftw/referencewidget/tests/widgets.py, ftw/referencewidget/widget.py
This way the widget behaves more like all other plone widgets.
I need to make this hack, because the template of the input element is a handlebars js template.
=> Render hidden input elements for stored references, instead of render them only by Javascript.

README.rst, docs/HISTORY.txt, ftw/referencewidget/behaviors.py, ftw/referencewidget/browser/generate_pathbar.py, ftw/referencewidget/browser/search.py, ftw/referencewidget/browser/utils.py, ftw/referencewidget/selectable.py, ftw/referencewidget/sources.py, ftw/referencewidget/tests/test_generate_pathbar.py, ftw/referencewidget/tests/test_relation_choice.py, ftw/referencewidget/tests/test_search_view.py, ftw/referencewidget/tests/test_source.py
I also moved from a selectable_function to a selectable_class since the logic to get the selectable content is going to be more complex now. 
This allows us for example to extend de default selector class. With a function we need copy the default logic every time.
=> Implement path restriction option

docs/HISTORY.txt, ftw/referencewidget/browser/jsongenerator.py, ftw/referencewidget/browser/search.py, ftw/referencewidget/tests/builders.py, ftw/referencewidget/tests/test_search_view.py, setup.py
Issue for this PR: https://github.com/4teamwork/bern.web/issues/1325
The date is shown for all Content Types which have set the start index. This includes eg. `Event` from plone or `ftw.news.News`
Eg. this would look like: "Some News Title (Oct 04, 2017)" or when you search for an item "Some News Title (Oct 04, 2017) (/path/to/item)"
=> Show localized news date in title for all news items

docs/HISTORY.txt, ftw/referencewidget/browser/search.py, ftw/referencewidget/locales/de/LC_MESSAGES/ftw.referencewidget.po, ftw/referencewidget/locales/ftw.referencewidget.pot, ftw/referencewidget/resources/refwidget.css, ftw/referencewidget/resources/refwidget.js, ftw/referencewidget/templates/handlebars.html, ftw/referencewidget/tests/test_search_view.py, ftw/referencewidget/widget.py
Issue for this PR: 4teamwork/bern.web#1325
Adds a checkbox to only search items which are below the current site level.
In this example you can see that if you are on the page 'Foo', you wont find the same called subpages which are in the Site `Bar`:
```
Search term:  "Some"
Current path: "/root/foo"
✕ /root
✕   /foo
✔       /Some Site
✕       /Other Site
✕   /bar
✕       /Some Site
✕       /Other Site
```
=> Add option to search in current path

ftw/referencewidget/browser/jsongenerator.py
Use  `item.start` instead of `item.news_date` like in https://github.com/4teamwork/ftw.referencewidget/blob/e49b149ac9246f3087fddb969f2b02f168bec08b/ftw/referencewidget/browser/search.py#L64
=> Fix wrong news date behind news in the jsongenerator.py

docs/HISTORY.txt, ftw/referencewidget/browser/jsongenerator.py, ftw/referencewidget/browser/search.py, ftw/referencewidget/resources/refwidget.js, ftw/referencewidget/tests/test_search_view.py
The first issue appeared if there was a umlaut in the title, since the localize datetime method returned a unicode.
The second problem was a browser problem, since $('some checkbox').val() always returns `on`.
=> Fix UniCodeDecodeError while displaying the news date and fix search in current path

docs/HISTORY.txt, ftw/referencewidget/behaviors.py
"plone.directives.form" is no longer installed automatically through one of our dependencies, probably because it was removed from "collective.z3cform.datagridfield" (see https://github.com/collective/collective.z3cform.datagridfield/blob/bff7b3be73fe22725cbf9c83ce45ebf710fc4693/CHANGES.rst#130-2017-11-22).
Fixes https://ci.4teamwork.ch/builds/126486/tasks/196675
=> No longer use "plone.directives.form".

docs/HISTORY.txt, ftw/referencewidget/converter.py
The referencewidget's converter for DataGrids expected a iterable value, even though the value could have been a None when the default for the Field was not set.
=> Fix error on loading a page with a DataGrid when its default is not set

test-plone-4.3.x-chameleon.cfg
"five.pt" has been marked as deprecated as the code has been integrated into "Zope2" >= 4. So they removed all the code from "five.pt" and released "five.pt" 3.0 which requires "Zope2" >= 4.0a2.
We cannot yet update to "Zope2" >= 4 so we need to use an older release of "five.pt".
=> Require "five.pt" < 3.0.

README.rst, docs/HISTORY.txt, ftw/referencewidget/configure.zcml, ftw/referencewidget/interfaces.py, ftw/referencewidget/profiles/default/metadata.xml, ftw/referencewidget/tests/test_utils.py, ftw/referencewidget/upgrades/20181112105705_fix_registry_field_frontend_edit/registry.xml, ftw/referencewidget/upgrades/20181112105705_fix_registry_field_frontend_edit/upgrade.py, setup.py
There was no version number set for the `ftw.referencewidget` package. As a result of this upgradesteps wont be shown in `../@@manage-upgrades` from [ftw.upgrade](https://github.com/4teamwork/ftw.upgrade).
So the first upgradesetp `Upgrade ftw.referencewidget:default to 20181112105705: Fix registry field frontend edit` must be installed via the ZMI under `../portal_setup/manage_fullImport`. This sets the version for the package and so further upgrades can be installed via `../@@manage-upgrades`.
Before 
After
=> Fix registry field frontend edit

ftw/referencewidget/configure.zcml
eliminates `WARNING plone.behavior Specifying 'for' in behavior 'Relation choice demo behavior' if no 'factory' is given has no effect and is superfluous.`
=> Remove superfluous "for" of behavior declarations.

ftw/referencewidget/resources/handlebars.js
Cooking a minified JavaScript often leads to compilation errors, therefore we should include the full JS source file rather than a minified version.
This fixes Plone 5 resource registry compilation.
=> Use unminified handlebars.

docs/HISTORY.txt, ftw/referencewidget/resources/handlebars.js
Plone 5 dev mode will not work otherwise.
=> Disable amd check for handlbar.js.

docs/HISTORY.txt, ftw/referencewidget/profiles/default/jsregistry.xml, ftw/referencewidget/upgrades/20200115110839_restrict_handle_bars_to_authenticated_users/jsregistry.xml, ftw/referencewidget/upgrades/20200115110839_restrict_handle_bars_to_authenticated_users/upgrade.py
In production mode, handlebar.js and refwidget.js weren't in the same 'Merged JS Compilation' file. This caused errors if the files were not loaded equally fast.
=> Ensure handlebars.js dependency is available for the product's JS

docs/HISTORY.txt, ftw/referencewidget/behaviors.py
Version 2 got a bigger refactoring, to avoid circular imports in collective.z3cform.datagridfield they removed those imports from one of the __init__.py's 
See https://github.com/collective/collective.z3cform.datagridfield/commit/3d4064a47a9062394acab8f2b65e61025875a150#diff-b7466768d5acffdf1a9b06abfb886a06ff495ef020cc04fea1b3d42b622c1c48
=> Fix DictRow, DataGridFieldFactory imports to be compatible with 1.x and 2.x of collective.z3cform.datagridfield.
